name: Daily Blog Generator

on:
  schedule:
    - cron: '0 7 * * 2-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "scripts/argos/.python-version"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5 # v8.1.0

      - name: "Set up Python"
        working-directory: scripts/argos
        run: uv sync --locked --all-extras --dev

      - name: "run script"
        working-directory: scripts/argos
        run: uv run main.py --config app/feeds/ai_research.yaml --output-type blogcast  --output ../../content/post/daily_ai/daily_ai_{date}.md --include-images --bundle --image-model krea/krea-2-medium-turbo
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Commit et Push des modifications
        run: |
          git config http.postBuffer 524288000
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto: Nouveau post de blog du $(date +'%Y-%m-%d')" || echo "Rien à commiter"
          git push
